
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const App = lazy(() => import("./pages/App.tsx"));
const CadastroPage = lazy(() => import("./pages/CadastroPage.tsx"));
const CampaignManagementPage = lazy(() => import("./pages/CampaignManagementPage.tsx"));
const CloudflareConfigPage = lazy(() => import("./pages/CloudflareConfigPage.tsx"));
const DashboardPage = lazy(() => import("./pages/DashboardPage.tsx"));
const LoginPage = lazy(() => import("./pages/LoginPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/cadastro-page", element: <CadastroPage />},
	{ path: "/cadastropage", element: <CadastroPage />},
	{ path: "/campaign-management-page", element: <UserGuard><CampaignManagementPage /></UserGuard>},
	{ path: "/campaignmanagementpage", element: <UserGuard><CampaignManagementPage /></UserGuard>},
	{ path: "/cloudflare-config-page", element: <UserGuard><CloudflareConfigPage /></UserGuard>},
	{ path: "/cloudflareconfigpage", element: <UserGuard><CloudflareConfigPage /></UserGuard>},
	{ path: "/dashboard-page", element: <UserGuard><DashboardPage /></UserGuard>},
	{ path: "/dashboardpage", element: <UserGuard><DashboardPage /></UserGuard>},
	{ path: "/login-page", element: <LoginPage />},
	{ path: "/loginpage", element: <LoginPage />},

];
